### ISSUE TITLE
ValueError for sunrise and sunset parameters on high Latitudes

### ISSUE THREAD

**Issue by make-ing** [meteomatics/python-connector-api#36]
When i run the following script i get this Error: ```ValueError: cannot convert float NaN to integer```
This is most likely due to the fact that at this latitude there are some days without a sunrise and sunset. Can you confirm this bug on your side? This is a currently a big issue on our side, and quick fix would be highly appreciated.

```
import meteomatics.api as api
from datetime import datetime, timedelta

USERNAME = <INSERT USERNAME HERE>
PASSWORD = <INSER PASSWORD HERE>


def main():
    data = api.query_time_series(
        coordinate_list=[(68, 13)],
        startdate=datetime(year=2021, month=1, day=1),
        enddate=datetime(year=2021, month=12, day=31),
        interval=timedelta(hours=1),
        parameters=['sunrise:sql', 'sunset:sql'],
        username=USERNAME,
        password=PASSWORD,
        model='mix',
    )
    print(data)


if __name__ == "__main__":
    main()
```

**Comment by meteomatics** [comment]
Good evening,
you can change the NaN behaviour through the `na_values` keyword. By supplying `na_values=[]` you should not get any NaN in the dataframe but the APIs native return values like -666 or -999.

Please let me know if this solves your issue.

**Comment by make-ing** [comment]
This workaround will fix the issue in case we just download the sunrise and sunset, but if we download other parameters as well where we need the -666 and other convertions it does not help.

**Comment by make-ing** [comment]
Ok i think in our special case we can get away with setting `na_values=[-666]` because the sunrise and sunset will only use -777 and -888 if i see it correctly. But i think this bug should still be fixed so that with the default values like above everything should work without an exception.

**Comment by meteomatics** [comment]
I maybe misunderstood the problem. The Meteomatics API has 4 reserved values with special meaning, as documented at https://www.meteomatics.com/en/api/response/reserved-values/#post-245968.
Those 4 values are by default converted to NaN by the connector. (Thus the default value for `NA_VALUES=(-666,-777,-888,-999)`) If you supply an empty list instead (`na_values=[]`) or overwrite the global `NA_VALUES` to an empty list, you prevent the connector from converting to NaN completely and thus you should not see any NaN in the answer independent of what parameters you request. If this is not what you are looking for, could you maybe explain your issue in more detail? Or write to support@meteomatics.com so that we can setup a direct support call.

**Comment by meteomatics** [comment]
Ah, and now I realize the Bug in there  (Sorry, I did not realize that the connector itself does not handle the NaN case.) We will look into this promptly.

**Comment by make-ing** [comment]
I think i understand how it works, but your programm clearly is not working as intended. In case of my request the api returns some values as `-777` and `-888` and according to your description above it should by default convert them to NaN. But it clearly does not work and throws an Exception. So your workaround works but only by effectifly turing the NaN convertion feature off.

**Comment by make-ing** [comment]
@maekke97: Thanks you very much for fixing it this quickly. Can you also push the fixed version to the CheeseShop (aka. pypi)?

**Comment by meteomatics** [comment]
Yes, version 2.3.2 should be available now.
